server:
  configLoadedMessage: "Config has loaded!"


fishingTable:
  cod:
    weight: 850
  salmon:
    weight: 200
  tropicalFish:
    weight: 150
  pufferfish:
    weight: 100
  nameTag:
    weight: 50
  bow:
    weight: 10
  enchantedBook:
    weight: 5
  enchantedGoldenApple:
    weight: 7
  saddle:
    weight: 10
  fishingRod:
    weight: 10
  nautilusShell:
    weight: 10
  lilyPad:
    weight: 15
  tripwireHook:
    weight: 15
  bowl:
    weight: 30
  leatherBoots:
    weight: 15
  leather:
    weight: 15
  leatherChestplate:
    weight: 15
  leatherHelmet:
    weight: 15
  leatherLeggings:
    weight: 15
  rottenFlesh:
    weight: 30
  bone:
    weight: 25
  string:
    weight: 15
  stick:
    weight: 30
  diamondSword:
    weight: 5
  diamondPickaxe:
    weight: 5
  diamondAxe:
    weight: 5
  diamondShovel:
    weight: 5
  diamondHelmet:
    weight: 5
  diamondChestplate:
    weight: 5
  diamondLeggings:
    weight: 5
  diamondBoots:
    weight: 5
  netheriteSmithingUpgrade:
    weight: 2
  heartOfTheSea:
    weight: 3
tiers:
  Exquisite:
    GENERIC_MAX_HEALTH: 10,
    GENERIC_FOLLOW_RANGE: 0,
    GENERIC_KNOCKBACK_RESISTANCE: 0,
    GENERIC_MOVEMENT_SPEED: 0,
    GENERIC_FLY_SPEED: 0,
    GENERIC_ATTACK_DAMAGE: 0,
    GENERIC_ATTACK_KNOCKBACK: 0,
    GENERIC_ATTACK_SPEED: 0,
    GENERIC_ARMOR: 0,
    GENERIC_ARMOR_TOUGHNESS: 0,
    GENERIC_LUCK: 0,
    GENERIC_MAX_ABSORPTION: 0,
    HORSE_JUMP_STRENGTH: 0,
    ZOMBIE_SPAWN_REINFORCEMENTS: 0
  Exceptional:
    GENERIC_MAX_HEALTH: 9,
    GENERIC_FOLLOW_RANGE: 0,
    GENERIC_KNOCKBACK_RESISTANCE: 0,
    GENERIC_MOVEMENT_SPEED: 0,
    GENERIC_FLY_SPEED: 0,
    GENERIC_ATTACK_DAMAGE: 0,
    GENERIC_ATTACK_KNOCKBACK: 0,
    GENERIC_ATTACK_SPEED: 0,
    GENERIC_ARMOR: 0,
    GENERIC_ARMOR_TOUGHNESS: 0,
    GENERIC_LUCK: 0,
    GENERIC_MAX_ABSORPTION: 0,
    HORSE_JUMP_STRENGTH: 0,
    ZOMBIE_SPAWN_REINFORCEMENTS: 0
  Superior:
    GENERIC_MAX_HEALTH: 8,
    GENERIC_FOLLOW_RANGE: 0,
    GENERIC_KNOCKBACK_RESISTANCE: 0,
    GENERIC_MOVEMENT_SPEED: 0,
    GENERIC_FLY_SPEED: 0,
    GENERIC_ATTACK_DAMAGE: 0,
    GENERIC_ATTACK_KNOCKBACK: 0,
    GENERIC_ATTACK_SPEED: 0,
    GENERIC_ARMOR: 0,
    GENERIC_ARMOR_TOUGHNESS: 0,
    GENERIC_LUCK: 0,
    GENERIC_MAX_ABSORPTION: 0,
    HORSE_JUMP_STRENGTH: 0,
    ZOMBIE_SPAWN_REINFORCEMENTS: 0
  Fine:
    GENERIC_MAX_HEALTH: 7,
    GENERIC_FOLLOW_RANGE: 0,
    GENERIC_KNOCKBACK_RESISTANCE: 0,
    GENERIC_MOVEMENT_SPEED: 0,
    GENERIC_FLY_SPEED: 0,
    GENERIC_ATTACK_DAMAGE: 0,
    GENERIC_ATTACK_KNOCKBACK: 0,
    GENERIC_ATTACK_SPEED: 0,
    GENERIC_ARMOR: 0,
    GENERIC_ARMOR_TOUGHNESS: 0,
    GENERIC_LUCK: 0,
    GENERIC_MAX_ABSORPTION: 0,
    HORSE_JUMP_STRENGTH: 0,
    ZOMBIE_SPAWN_REINFORCEMENTS: 0
  Decent:
    GENERIC_MAX_HEALTH: 6,
    GENERIC_FOLLOW_RANGE: 0,
    GENERIC_KNOCKBACK_RESISTANCE: 0,
    GENERIC_MOVEMENT_SPEED: 0,
    GENERIC_FLY_SPEED: 0,
    GENERIC_ATTACK_DAMAGE: 0,
    GENERIC_ATTACK_KNOCKBACK: 0,
    GENERIC_ATTACK_SPEED: 0,
    GENERIC_ARMOR: 0,
    GENERIC_ARMOR_TOUGHNESS: 0,
    GENERIC_LUCK: 0,
    GENERIC_MAX_ABSORPTION: 0,
    HORSE_JUMP_STRENGTH: 0,
    ZOMBIE_SPAWN_REINFORCEMENTS: 0
  Average:
    GENERIC_MAX_HEALTH: 5,
    GENERIC_FOLLOW_RANGE: 0,
    GENERIC_KNOCKBACK_RESISTANCE: 0,
    GENERIC_MOVEMENT_SPEED: 0,
    GENERIC_FLY_SPEED: 0,
    GENERIC_ATTACK_DAMAGE: 0,
    GENERIC_ATTACK_KNOCKBACK: 0,
    GENERIC_ATTACK_SPEED: 0,
    GENERIC_ARMOR: 0,
    GENERIC_ARMOR_TOUGHNESS: 0,
    GENERIC_LUCK: 0,
    GENERIC_MAX_ABSORPTION: 0,
    HORSE_JUMP_STRENGTH: 0,
    ZOMBIE_SPAWN_REINFORCEMENTS: 0
  Worn:
    GENERIC_MAX_HEALTH: 4,
    GENERIC_FOLLOW_RANGE: 0,
    GENERIC_KNOCKBACK_RESISTANCE: 0,
    GENERIC_MOVEMENT_SPEED: 0,
    GENERIC_FLY_SPEED: 0,
    GENERIC_ATTACK_DAMAGE: 0,
    GENERIC_ATTACK_KNOCKBACK: 0,
    GENERIC_ATTACK_SPEED: 0,
    GENERIC_ARMOR: 0,
    GENERIC_ARMOR_TOUGHNESS: 0,
    GENERIC_LUCK: 0,
    GENERIC_MAX_ABSORPTION: 0,
    HORSE_JUMP_STRENGTH: 0,
    ZOMBIE_SPAWN_REINFORCEMENTS: 0
  Shoddy:
    GENERIC_MAX_HEALTH: 3,
    GENERIC_FOLLOW_RANGE: 0,
    GENERIC_KNOCKBACK_RESISTANCE: 0,
    GENERIC_MOVEMENT_SPEED: 0,
    GENERIC_FLY_SPEED: 0,
    GENERIC_ATTACK_DAMAGE: 0,
    GENERIC_ATTACK_KNOCKBACK: 0,
    GENERIC_ATTACK_SPEED: 0,
    GENERIC_ARMOR: 0,
    GENERIC_ARMOR_TOUGHNESS: 0,
    GENERIC_LUCK: 0,
    GENERIC_MAX_ABSORPTION: 0,
    HORSE_JUMP_STRENGTH: 0,
    ZOMBIE_SPAWN_REINFORCEMENTS: 0
  Rusty:
    GENERIC_MAX_HEALTH: 2,
    GENERIC_FOLLOW_RANGE: 0,
    GENERIC_KNOCKBACK_RESISTANCE: 0,
    GENERIC_MOVEMENT_SPEED: 0,
    GENERIC_FLY_SPEED: 0,
    GENERIC_ATTACK_DAMAGE: 0,
    GENERIC_ATTACK_KNOCKBACK: 0,
    GENERIC_ATTACK_SPEED: 0,
    GENERIC_ARMOR: 0,
    GENERIC_ARMOR_TOUGHNESS: 0,
    GENERIC_LUCK: 0,
    GENERIC_MAX_ABSORPTION: 0,
    HORSE_JUMP_STRENGTH: 0,
    ZOMBIE_SPAWN_REINFORCEMENTS: 0
  Scrap:
    GENERIC_MAX_HEALTH: 1,
    GENERIC_FOLLOW_RANGE: 0,
    GENERIC_KNOCKBACK_RESISTANCE: 0,
    GENERIC_MOVEMENT_SPEED: 0,
    GENERIC_FLY_SPEED: 0,
    GENERIC_ATTACK_DAMAGE: 0,
    GENERIC_ATTACK_KNOCKBACK: 0,
    GENERIC_ATTACK_SPEED: 0,
    GENERIC_ARMOR: 0,
    GENERIC_ARMOR_TOUGHNESS: 0,
    GENERIC_LUCK: 0,
    GENERIC_MAX_ABSORPTION: 0,
    HORSE_JUMP_STRENGTH: 0,
    ZOMBIE_SPAWN_REINFORCEMENTS: 0