server:
  configLoadedMessage: "Config has loaded!"

fishingTable:
  cod:
    weight: 850
  salmon:
    weight: 200
  tropicalFish:
    weight: 150
  pufferfish:
    weight: 100
  nameTag:
    weight: 50
  bow:
    weight: 10
  enchantedBook:
    weight: 5
  enchantedGoldenApple:
    weight: 7
  saddle:
    weight: 10
  fishingRod:
    weight: 10
  nautilusShell:
    weight: 10
  lilyPad:
    weight: 15
  tripwireHook:
    weight: 15
  bowl:
    weight: 30
  leatherBoots:
    weight: 15
  leather:
    weight: 15
  leatherChestplate:
    weight: 15
  leatherHelmet:
    weight: 15
  leatherLeggings:
    weight: 15
  rottenFlesh:
    weight: 30
  bone:
    weight: 25
  string:
    weight: 15
  stick:
    weight: 30
  diamondSword:
    weight: 5
  diamondPickaxe:
    weight: 5
  diamondAxe:
    weight: 5
  diamondShovel:
    weight: 5
  diamondHelmet:
    weight: 5
  diamondChestplate:
    weight: 5
  diamondLeggings:
    weight: 5
  diamondBoots:
    weight: 5
  netheriteSmithingUpgrade:
    weight: 2
  heartOfTheSea:
    weight: 3