name: SurvivalOverhaul
version: '${project.version}'
main: org.laykon.survivaloverhaul.SurvivalOverhaul
api-version: '1.20'

commands:
  fly:
    permission: "so.fly"
  dev/giveolympian:
    permission: "so.olympian"
  feed:
    permission: "so.feed"
  dtn:
    permission: "so.dtn"
  spawnboss:
    permission: "so.spawnboss"
  dev/data/write:
    permission: "so.writedata"
  dev/data/read:
    permission: "so.readdata"