name: SurvivalOverhaul
version: '${project.version}'
main: org.laykon.survivaloverhaul.SurvivalOverhaul
api-version: '1.20'

commands:
  fly:
    permission: "so.fly"
  dev/giveolympian:
    permission: "so.olympian"
  feed:
    permission: "so.feed"